swagger: "2.0"
info:
  description: API for https://github.com/Code42Cate/google-news-sucks
  version: "1.0.0"
  title: Google News Sucks API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1"

paths:
  /articles:
    get:
      operationId: "api.get_articles"
      tags:
        - "Articles"
      summary: "The articles data structure supported by the server application, without content of the articles"
      description: "Read complete list of articles"
      responses:
        200:
          description: "Successful read articles list operation"
          schema:
            type: "array"
            items:
              properties:
                url:
                  type: "string"
                title:
                  type: "string"
                keywords:
                  type: array
                  items:
                    type: string
                categories:
                  type: array
                  items:
                    type: string
  /categories/{keyword}:
    patch:
      operationId: "api.update_keyword"
      tags:
        - "Keywords"
        - "Categories"
      summary: "Adds the category to the categories set from the given keyword"
      parameters:
      - name: keyword
        in: path
        description: Keyword that should get updated
        type: string
        required: True
      - name: category
        in: body
        required: True
        schema:
          type: object
          properties:
            category:
              type: string
              description: Category to be added
      responses:
        200:
          description: "Added category"
